federation_version: 2
subgraphs:
  person:
    routing_url: http://localhost:5011/graphql
    schema:
      subgraph_url: http://localhost:5011/graphql
  relationship:
    routing_url: http://localhost:5012/graphql
    schema:
      subgraph_url: http://localhost:5012/graphql
  asset:
    routing_url: http://localhost:5013/graphql
    schema:
      subgraph_url: http://localhost:5013/graphql
  balance:
    routing_url: http://localhost:5014/graphql
    schema:
      subgraph_url: http://localhost:5014/graphql
  plausibility:
    routing_url: http://localhost:5015/graphql
    schema:
      subgraph_url: http://localhost:5015/graphql
  product:
    routing_url: http://localhost:5016/graphql
    schema:
      subgraph_url: http://localhost:5016/graphql
